version: "3"
services:
    workspace:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                SSH_PASSWORD: password
        volumes:
            - code-workspace:/root/workspace
        ports:
            - "8080:80"
            - "8443:443"
            - "2222:22"
volumes:
    code-workspace:
        name: "code-workspace"
